version: "3.8"
services:
  hotels50k:
    build: .
    volumes:
        - "./input:/HOTELS-50K/input"
        - "./images:/HOTELS-50K/images"
    tty: true
    stdin_open: true
    entrypoint :  
        - /bin/bash
